"""Add knowledge_tag to StudentAnswerRecord

Revision ID: e1724f3e0110
Revises: e5d27a35caaf
Create Date: 2025-06-21 13:58:30.508378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1724f3e0110'
down_revision = 'e5d27a35caaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answer_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_tag', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answer_record', schema=None) as batch_op:
        batch_op.drop_column('knowledge_tag')

    # ### end Alembic commands ###
