"""add created_at to StudentAnswerRecord

Revision ID: e5d27a35caaf
Revises: 6de7a3f13e35
Create Date: 2025-06-21 11:46:53.654100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d27a35caaf'
down_revision = '6de7a3f13e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answer_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answer_record', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
